### ISSUE TITLE
UnboundLocalError: local variable 'attachment' referenced before assignment

### ISSUE THREAD

**Issue by sgohl** [mtorromeo/slacksend#1]
Hi,
I can't get it working :-(

First, I had to install some python extensions: setproctitle, configparser, pathlib
Then, I ran: 

`./slacksend.py -U https://hooks.slack.com/services/T0NKTg74E/B1KN30Cx2/5a2kZ6LtJJwEixd "bla"`

(token anonymized) and it gives back:

```
Traceback (most recent call last):
  File "./slacksend.py", line 122, in <module>
    main()
  File "./slacksend.py", line 115, in main
    payload = build(options, args, message)
  File "./slacksend.py", line 21, in build
    if attachment:
UnboundLocalError: local variable 'attachment' referenced before assignment
```

I tested that on different machines, all the same ..

**Comment by mtorromeo** [comment]
Hi,
the commit should fix this issue but in the long term I plan to merge this with [mattersend](/mtorromeo/mattersend) which is better maintained, so that there will be a single tool which works with both slack and mattermost.

**Comment by sgohl** [comment]
ooh alright, I din't know I could use mattersend for slack too - i'll test that. thanks!

**Comment by mtorromeo** [comment]
Not yet. It's something I have planned. Hopefully you'll be able to use slacksend in the meantime.
